//
//  GamesData.swift
//  ScreenTime
//
//  Created by BigOof on 12/9/19.
//  Copyright © 2019 Olivier Balazy. All rights reserved.
//

import Foundation
import UIKit

func encodeDataOverall(){
    defaults.set(try? PropertyListEncoder().encode(overallGames), forKey: "gameDataOverall")
}

func decodeDataOverall()->[Game]{
    guard let gamesData = defaults.object(forKey: "gameDataOverall") as? Data else{
        return []
    }
    
    guard let games = try? PropertyListDecoder().decode([Game].self, from: gamesData) else {
        return []
    }

    return games
    
}
func encodeDataBasic(){
    defaults.set(try? PropertyListEncoder().encode(basicGames), forKey: "gameDataBasic")
}

func decodeDataBasic()->[Game]{
    guard let gamesData = defaults.object(forKey: "gameDataBasic") as? Data else{
        return []
    }
    
    guard let games = try? PropertyListDecoder().decode([Game].self, from: gamesData) else {
        return []
    }
    
    return games
    
}
func encodeDataAdvanced(){
    defaults.set(try? PropertyListEncoder().encode(advancedGames), forKey: "gameDataAdvanced")
}

func decodeDataAdvanced()->[Game]{
    guard let gamesData = defaults.object(forKey: "gameDataAdvanced") as? Data else{
        return []
    }
    
    guard let games = try? PropertyListDecoder().decode([Game].self, from: gamesData) else {
        return []
    }
    
    return games
    
}

func createGames(){
    
    //adds games from methods below to arrays
    basicGames = createBasicGames()
    advancedGames = createAdvancedGames()
    overallGames += basicGames
    overallGames += advancedGames
    
}

//adds games to basicGames array
func createBasicGames() ->[Game]{
    
    var tempGames: [Game] = []
    var index = 0
    //Use \u{2022} for bulletpoints and \n\n for ordered lists
    tempGames.append(Game(catagory: "card", title: "Battle", image: "battle", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022} At least 1 deck of cards", rules: "1. Split the deck into two face down piles and give each person a pile.\n\n2. Each round, everyone grabs a card from their pile and places it face up in the middle.\n\n3. The person with the higher numbered card gets to take both cards and put it in a new pile off to the side.\n\n4. If the numbers are the same, take out two cards but only flip the second one face up. The higher number takes all the cards. You can repeat it as many times as it takes until there is one winner.", favorite: false, gameIndex: index))
    //must have the line below
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Go Fish", image: "goFish", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022} At least 1 deck of cards", rules: "1. Five cards are dealt to each player if three to six players are involved. With only two players, seven cards are dealt to each. All remaining cards are placed face down in a pile.\n\n2. Choose a player to go first. On each person’s turn, ask any player for a specific card rank. You must already hold at least one card of the rank you ask for.\n\n3. If the player you ask has any cards of the requested rank, she must give all of her cards of that rank to you.\n\n4. If you get one or more cards from the player you ask, you get another turn.\n\n5. It starts again and you may ask any player for any rank you already hold, including the same one you just asked for. If the person you ask has no relevant cards, they say, “Go Fish.”\n\n6. You then draw the top card from the draw pile. If you happen to draw a card of the rank asked for, show it to the other players and your turn continues. Otherwise, it is the next player’s turn who said “Go Fish”. You add the drawn card to your hand.\n\n7. When you collect a set of four cards of the same rank, immediately show the set to the other players and place the four cards face down in front of yourself. That is a “match”.\n\n8. Go fish continues until either someone has no cards left in their hand or the draw pile runs out.\n\n9. The winner is the player who has the most matches.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "dice", title: "Knock out", image: "knockOutAndBeatThatAndRoundTheClock", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022} 2 dice", rules: "1. Each player chooses a “knock out number” – either 6, 7, 8, or 9. More than one player can choose the same number.\n\n2. Players take turns throwing both dice, once each turn. Add the number of both dice for the score.\n\n3. If a player throws a 6, 7, or 8, they are knocked out of the game until the next round.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Crazy Eights", image: "crazyEights", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022} At least 1 deck of cards", rules: "1. Each player is dealt seven cards. The remaining cards are placed face down in the center of the table, forming a draw pile.\n\n2. The top card of the draw pile is turned face up to start the discard pile next to it.\n\n3. First player adds to the discard pile by playing one card that matches the top card on the discard pile either by suit or by rank.\n\n4. A player who cannot match the top card on the discard pile by suit or rank must draw cards until he can play one.\n\n5. All eights are wild and can be played on any card during a player’s turn.\n\n6. All eights are wild and can be played on any card during a player’s turn.\n\n7. When a player discards an eight, he chooses which suit is now in play.\n\n8. The next player must either play a card of that suit or another eight.\n\n9. The first player to discard all of his cards wins. ", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Spoons", image: "spoons", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022} At least 1 deck of cards", rules: "1. Place the spoons evenly along a table. Each player is dealt four cards from two shuffled decks.\n\n2. The designated dealer of the first round begins by picking the top card from the pile in front of them, deciding whether it will help them get four of a kind, then discard a card to the player to their left. They in turn decide if this card will help them, then discard to the player on their left, and so on.\n\n3. When play reaches the person to the dealer’s right, their discarded card is left to create a second pile. Play continues with the dealer again taking a card from the central pile.If the dealer runs out of cards from the central pile, they pick from the second pile between them and the player to their right.\n\n4. When someone gets four of a kind, they must grab a spoon and everyone else must follow. The player left empty-handed is eliminated and a spoon is removed from the stash.\n\n5. The game continues, with the dealer moving one position to the left, until the final two-person, one-spoon showdown.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Memory", image: "memory", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022} At least 1 deck of cards", rules: "1. Mix up the cards.\n\n2. Lay them in rows, face down.\n\n3. Turn over any two cards.\n\n4. If the two cards match, keep them. If they don’t match, turn them back over.\n\n5. Remember what was on each card and where it was.\n\n6. Watch and remember during the other player’s turn.\n\n7. The game is over when all the cards have been matched.\n\n8. The player with the most matches wins.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Old Maid", image: "oldMaid", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022} At least 1 deck of cards", rules: "1. Before dealing, players much decide whether or not to add a card (like a Joker or a card from an identical deck) or to subtract a card (typically the Queens of Clubs) to serve as the Old Maid.\n\n2. Shuffle, and deal all the cards. Players sort through their cards, making as many pairs as possible, and placing these pairs face-up on the table in front of them.\n\n3. Starting with the dealer, each player then takes a turn fanning out their hands so that the player to their left can draw one card.\n\n4. The player must not be allowed to see the player’s hand from which they are drawing. Play continues in this fashion.\n\n5. As players make pairs in their hand, they discard them immediately onto the table.\n\n6. Whoever is left with the Old Maid as their last card loses.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "strategy", title: "Checkers", image: "checkers", difficulty: "", playerAmountLow: 2, playerAmountHigh: 2, materials: "\u{2022} Gameboard, checkers", rules: "1. Take 12 checkers of the same color and place them on all of the dark squares of the first three rows in front of you. Your opponent does the same.\n\n2. Choose a player to go first. On your turn, move any one of your checkers by the movement rules described below. After you move one checker, your turn is over. The game continues with players alternating turns.\n\n\ta. Always move your checker diagonally forward, toward your opponent’s side of the game board. (After a checker becomes a “King,” it can move diagonally forward or backward.\n\n\tb. Move your checker one space diagonally, to an open adjacent square; or jump one or more checkers diagonally to an open square adjacent to the checker you jumped. When jump over an opponent’s checker, you capture it.\n\n\tc. If all squares adjacent to your checker are occupied, your checker is blocked and cannot move.\n\n3. If you jump an opponent’s checker, you capture it. Remove it from the game board and place it in front of you.\n\n4. As soon as one of your checkers reaches the first row on your opponent’s side of the game board, it becomes a King.\n\n5. Place another checker of the same color on top of it. Now this double-decker checker can move forward or backward on the game board.\n\n6. The first player to capture all opposing checkers from the game board wins the game!", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "dice", title: "Beat That!", image: "knockOutAndBeatThatAndRoundTheClock", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022} 2 Dice", rules: "1. Each player takes a turn rolling the dice and placing them in order to make the highest number possible. For example, if a player throws a two and a three, they have 23.\n\n2. A player who throws a six and a four would win the round as they have the higher number.\n\n3. After each throw, a player challenges the next player, “Beat that!” Play this game in rounds, assigning a winner to each round.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "dice", title: "Going to Boston", image: "knockOutAndBeatThatAndRoundTheClock", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022} 3 Dice", rules: "1. Roll the dice and keep the highest.\n\n2. Roll the remaining dice and again set aside the highest.\n\n3. Roll the last die, and add up your total. Write down your score.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "active", title: "Tag", image: "freezeTag", difficulty: "", playerAmountLow: 3, playerAmountHigh: 0, materials: "\u{2022} Nothing else needed", rules: "1. Decide who is “It”. This person will chase the other players, trying to tag them, until he/she tags someone. Then, the tagged person becomes “It,’ and the original “it” person runs away to avoid being tagged.\n\n2. Choose the playing area. Set boundaries so that the “not-it” players can’t run too far away.\n\n3. Count out a head start for running. The “It” person counts out a ten-seconds head start to give the “not-it” players time to run away. Everyone who is “not it” will run away from the person who is “it” and try to avoid getting tagged.\n\n4. The “It” player tries to touch another player in order to make them “it”. Once the “it” player succeeds in tagging someone, the tagged player is now “it”.\n\n5. As the tagged player: yell loud enough for everyone to hear that you are now “It”.\n\n6. Once a person has been tagged, continue the game with the new “it” player trying to tag someone. The game continues in this way for as long as you want to keep playing.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "active", title: "Freeze Tag", image: "freezeTag", difficulty: "", playerAmountLow: 3, playerAmountHigh: 0, materials: "\u{2022} Nothing else needed", rules: "1. To begin, the players spread out within the open area, and the leader designates who the taggers are, what position frozen people move into, what is needed to unfreeze someone, and how long games will be.\n\n2. If a player gets tagged, they move into the frozen position. It can be anything from sitting on the ground to how they were when they got tagged.\n\n3. To unfreeze a player, another player must do the action the leader chose, like a double high five or a hug.\n\n4. No one can be tagged while unfreezing someone and taggers cannot stand around waiting for them to finish.\n\n5. The taggers win if they freeze everyone, and they lose if the time runs out and someone is still unfrozen.\n\n6. The taggers should be different people each round.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "active", title: "Hide and Seek", image: "hideAndSeek", difficulty: "", playerAmountLow: 3, playerAmountHigh: 0, materials: "\u{2022} Nothing else needed", rules: "1. Gather the group together and choose one person to be “it”. This person is the seeker and must look for everyone else. The rest of the group must hide in the designated area.\n\n2. First, decide and agree upon a spot to be home base.\n\n3. The person who is “it” stands on the home base, covers his eyes and counts to a previously agreed upon number. Usually about 30 seconds will give hiders opportunity to choose a spot and stow away.\n\n4. When through counting, the “it” person says loudly, “Ready or not, here I come!” and runs to find the other players.\n\n5. The hiders must remain very quiet, and the last person to remain hiding without being found is the winner, and chooses the next person to be “it”.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "active", title: "Red Light, Green Light", image: "redLightGreenLight", difficulty: "", playerAmountLow: 3, playerAmountHigh: 0, materials: "\u{2022} Nothing else needed", rules: "1. The players line up, side-by-side at one end of the playing space facing the leader.\n\n2. The leader stands opposite the players, facing them.\n\n3. When the leader shouts Green Light! the players move toward the leader. Instruct them to walk, speed walk, or run, depending on the amount of space you have for playing the game.\n\n4. When the leader shouts Red Light! the players stop where they are.\n\n5. The leader continues to shout Red Light! and Green Light! until a player reach them. That player is the winner of the round and becomes the next leader.\n\n6. All the players go back to the starting line and the game begins again.", favorite: false, gameIndex: index))
        index += 1
        
        tempGames.append(Game(catagory: "active", title: "Shadow Tag", image: "shadowTag", difficulty: "", playerAmountLow: 3, playerAmountHigh: 0, materials: "\u{2022}A sunny day", rules: "1. Spread out in the area you will play in.\n\n2. Run around and tag people by steping on their shadow.\n\n3. If you are tagged, you have to sit down.\n\n4. The last person standing wins.", favorite: false, gameIndex: index))
        index += 1
        
        tempGames.append(Game(catagory: "active", title: "Monkey in the Middle", image: "monkeyInTheMiddle", difficulty: "", playerAmountLow: 3, playerAmountHigh: 0, materials: "\u{2022}A ball", rules: "1. Decide who’s the monkey and who starts with the ball.\n\n2. Form a circle and spread out. The monkey stands in the middle and everyone else should form a large circle around the monkey.\n\n3. The person who has the ball has to throw the ball to someone in the circle besides the monkey.\n\n4. Everyone can move around as long as the ball not being held.\n\n5. If the ball is held by someone, everyone has to go back to their spots in the circle.\n\n6. If the monkey gets the ball, whoever threw the ball has to switch spots with them, and become the new monkey.\n\n7. Continue playing the game until everyone gets a turn in the middle.", favorite: false, gameIndex: index))
        index += 1
        
        tempGames.append(Game(catagory: "active", title: "Four Corner", image: "shadowTag", difficulty: "", playerAmountLow: 3, playerAmountHigh: 0, materials: "\u{2022}Nothing else needed", rules: "1. The player in the middle must close their eyes and count slowly and loudly backward from ten to zero.\n\n2. While they are counting, everyone must find a corner and stay there or they are out.\n\n3. The player in the middle points to corner of their choice, and then opens their eyes.\n\n4. Anyone standing in the chosen corner must sit down.\n\n5. If no one is in that corner, all the eliminated players sitting may stand up and get back into the game.\n\n6. When only one player is left standing, they becomes the middle player for the next round.", favorite: false, gameIndex: index))
        index += 1
        
        tempGames.append(Game(catagory: "active", title: "Four Square", image: "fourSquare", difficulty: "", playerAmountLow: 4, playerAmountHigh: 0, materials: "\u{2022}A ball", rules: "1. Each player stands in one of the four squares.\n\n2. To start the game, the player in square four serves the ball by bouncing it in their square once and then hitting it towards one of the other squares. The receiving player then hits the ball to any other player in one of the squares.\n\n3. The ball must bounce in another player’s square, and they must hit it to another player before it bounces a second time.\n\n4. A player can hit the ball before it bounces, if they want.\n\n5. If a player hits the ball outside of all the squares, or doesn't hit the ball before the second bounce after it has landed in their square, they are “out”.\n\n6. When a player is out, the other players move up to take their place, and that player moves to the last square, or to the end of the line, if there are more than four players. If there is a line, the first person in it will go to the last square.\n\n7. The object of the game is to move up to and hold the first square.", favorite: false, gameIndex: index))
        index += 1
        
        tempGames.append(Game(catagory: "dice", title: "Pig", image: "knockOutAndBeatThatAndRoundTheClock", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022}A dice", rules: "1. On a turn, a player rolls the die repeatedly. The goal is to accumulate as many points as possible, adding up the numbers rolled on the die. However, if a player rolls a 1, the player’s turn is over and any points they have accumulated during the turn are forfeited. Rolling a 1 doesn’t wipe out your entire score from previous turns, just the total earned during that particular roll.\n\n2. A player can also choose to hold (stop rolling the die) if they do not want to take a chance of rolling a 1 and losing all of their points from this turn. If the player chooses to hold, all of the points rolled during that turn are added to his or her score.\n\n3. When a player reaches a total of 100 or more points, the game ends and that players is the winner.", favorite: false, gameIndex: index))
        index += 1
        
        tempGames.append(Game(catagory: "dice", title: "Run for it", image: "knockOutAndBeatThatAndRoundTheClock", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022}6 dice", rules: "1. Each player takes a turn rolling the dice and looking for runs starting with (1-2, 1-2-3, and so on).\n\n2. Each dice part of the run scores five points. A player can only have one run in each roll.\n\n3. The first who reaches 100 points is the winner.", favorite: false, gameIndex: index))
        index += 1
        
        tempGames.append(Game(catagory: "dice", title: "Stuck in the Mud", image: "stuckInTheMudAndThreeOrMore", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022}5 dice", rules: "1. The first player rolls all five dice. If any 2s or 5s are rolled, no points are scored for this throw. If no 2s or 5s are rolled, add up the total of the dice and write it down.\n\n2. The player sets aside any 2s and 5s, and throws the remaining dice. Again, if any 2s or 5s are thrown, no points are scored. If there are no 2’s or 5s, add the total to the previous score.\n\n3. Continue in this way until all the dice are “Stuck in the Mud,” meaning that they are all 2’s and 5’s. After the score is totaled, the person to the left goes next.\n\n4. The person with the highest score after everyone has gone is the winner.", favorite: false, gameIndex: index))
        index += 1
        
        tempGames.append(Game(catagory: "dice", title: "Three or More", image: "stuckInTheMudAndThreeOrMore", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022}5 dice", rules: "1. Players take turns rolling all five dice and scoring for three-of-a-kind or better.\n\n2. If a player only has two-of-a-kind, they may re-throw the remaining dice in an attempt to improve the matching dice values.\n\n3. If no matching numbers are rolled, a player scores 0.\n\n4. If they get 3 of a kind, they get 1 point, 4 of a kind gets 2 points, and 5 of a kind gets 4 points!\n\n5. The person with the highest score after everyone has gone 4 times is the winner.", favorite: false, gameIndex: index))
        index += 1
        
        tempGames.append(Game(catagory: "dice", title: "Round the Clock", image: "knockOutAndBeatThatAndRoundTheClock", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022}2 dice", rules: "1. Choose the first player with a dice throw; the player with the lowest total going first.\n\n2. The first player throws both dice, hoping to throw a 1. Players then take turns (in a clockwise direction) trying to throw a 1.\n\n3. On the next round, those players who threw throw a 1 will try to throw a 2. Any player who did not throw a 1 in the first round will try again this round. Players can do so by throwing a 2 or two 1s.\n\n4. Play continues round-by-round with players trying to throw all the numbers from 1 to 12 in sequence. Players may count the spots on just one die or on both dice added together. For example, throwing a 3 and a 6 could be counted as 3, 6, or 9.\n\n5. The first player to go “Round the Clock” – throw all the numbers from 1 to 12 in order – wins the game.", favorite: false, gameIndex: index))
        index += 1

    
    
    return tempGames
    
}

//adds games to advancedGames array
func createAdvancedGames() ->[Game]{
    
    var tempGames: [Game] = []
    var index = 0
    //Use \u{2022} for bulletpoints and \n\n for ordered lists
    tempGames.append(Game(catagory: "card", title: "Crazy Eights", image: "crazyEights", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022} At least 1 deck of cards", rules: "1. Five cards are dealt to each player (or seven in a two-player game). The remaining cards of the deck are placed face down at the center of the table. The top card is then turned face up to start the game.\n\n2. Players discard by matching rank or suit with the top card of the discard pile, starting with the player left of the dealer. They can also play any 8 at any time. If a player is unable to match the rank or suit of the top card of the discard pile and does not have an 8, they draw a card from the stockpile. When a player plays an 8, they must declare the suit that the next player is to play; that player must then follow the named suit or play another 8.\n\n3. As an example: Once 6♣ is played the next player:\ncan play any of the other 6s\ncan play any of the clubs\ncan play any 8 (then must declare a suit)\ncan draw from the stockpile until willing and able to play one of the above\n\n4.The game ends as soon as one player has emptied their hand. That player collects a payment from each opponent equal to the point score of the cards remaining in that opponent's hand. 8s score 50, court cards 10 and all other cards face value. If the players run out of cards in the deck, the player with the lowest point score in their hand scores the difference between that hand and each opponent's hand.\n\n5. The winner of the game is the first player to reach a specific number of points. For two players it is 100 points, three players 150, four 200, five 250, six 300 and for seven players 350.", favorite: false, gameIndex: index))
    //must have the line below
    index += 1
    
    tempGames.append(Game(catagory: "strategy", title: "Connect 4", image: "connectFour", difficulty: "", playerAmountLow: 2, playerAmountHigh: 2, materials: "\u{2022} Gameboard, checkers", rules: "1. Set up the board by attaching the grid to the base or sliding the supports onto the sides of the grid. Place the grid between the two players.\n\n2. Slide the lever at the bottom of the grid into the locked position.\n\n3. Divide the checkers evenly between players. The classic colors are red and black, but other variations include red and yellow and black and white.\n\n4. Determine which player goes first. This may be done using any random method, such as flipping a coin. It’s common to let the youngest player go first when playing with children.\n\n5. The first player inserts a checker into the grid. Only after the checker has been released can the second player make his or her move.\n\n6. Turns continue to alternate between the first and second players until someone gets four checkers of the same color lined up in a row or the board is filled without any winning moves.\n\n7. After a winner has been determined or a tie declared, place the box underneath the grid. Slide the lever out of the locked position to release the checkers.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "strategy", title: "Checkers", image: "checkers", difficulty: "", playerAmountLow: 2, playerAmountHigh: 2, materials: "\u{2022} Gameboard, checkers", rules: "1. Take 12 checkers of the same color and place them on all of the dark squares of the first three rows in front of you. Your opponent does the same.\n\n2. Choose a player to go first. On your turn, move any one of your checkers by the movement rules described below. After you move one checker, your turn is over. The game continues with players alternating turns.\n\n\ta. Always move your checker diagonally forward, toward your opponent’s side of the game board. (After a checker becomes a “King,” it can move diagonally forward or backward.\n\n\tb. Move your checker one space diagonally, to an open adjacent square; or jump one or more checkers diagonally to an open square adjacent to the checker you jumped. When jump over an opponent’s checker, you capture it.\n\n\tc. If all squares adjacent to your checker are occupied, your checker is blocked and cannot move.\n\n3. If you jump an opponent’s checker, you capture it. Remove it from the game board and place it in front of you.\n\n4. As soon as one of your checkers reaches the first row on your opponent’s side of the game board, it becomes a King.\n\n5. Place another checker of the same color on top of it. Now this double-decker checker can move forward or backward on the game board.\n\n6. The first player to capture all opposing checkers from the game board wins the game!", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Klondike", image: "anySolitaireGames", difficulty: "", playerAmountLow: 1, playerAmountHigh: 1, materials: "\u{2022} At least 1 deck of cards", rules: "1. Deal out 28 cards in seven piles as follows: The first pile is one card; the second pile has two cards, and so on up to seven in the last pile. The top card of each pile is face up; all others are face down.\n\n2. The four aces form the foundations. As it becomes available, each ace must be played to a row above the piles. Cards in the appropriate suit are then played on the aces in sequence - the two, then the three, and so on - as they become available.\n\n3. Any movable card may be placed on a card next-higher in rank if it is of opposite color. Example: A black five may be played on a red six. If more than one card is face up on a tableau pile, all such cards must be moved as a unit.\n\n4. When there is no face-up card left on a pile, the top face-down card is turned up and becomes available.\n\n5. Only a king may fill an open space in the layout. The player turns up cards from the top of the stock in groups of three, and the top card of the three may be used for building on the piles, if possible, played on a foundation. If a card is used in this manner, the card below it becomes available for play. If the up-card cannot be used, the one, two, or three cards of the group are placed face up on the waste pile, and the next group of three cards is turned up.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Spider", image: "anySolitaireGames", difficulty: "", playerAmountLow: 1, playerAmountHigh: 1, materials: "\u{2022} At least 1 deck of cards", rules: "1. Ten piles of five cards each are dealt by rows. The first four cards of each pile are dealt face down, the top cards face up.\n\n2. The top card of a pile may be moved, together with all face-up cards below it that follow in ascending suit and sequence.\n\n3. A sequence of available cards may be broken at any point by leaving some cards behind. Example: If a pile from top down shows 4, 5, 6, 7, either the first one, two, or three cards may be moved as a unit, but the 7 may not be moved until the covering three cards are removed. When all face-up cards on a pile are removed, the next card below is turned face up and becomes available.\n\n4. A movable unit of cards may be placed either in a space or on a card of the next-higher rank to the bottom card of the unit, regardless of color or suit. Example: If the bottom card of a unit is the J, it may be moved onto any one of the four queens.\n\n5. A king can be moved only onto a space. Alternatively, the spaces may be filled with any movable unit.\n\n6. When all possible or desired moves come to a standstill, the player deals another row of ten cards face up. However, before such a deal may be made, all spaces must be filled. The final deal consists of only four cards, which are placed on the first four piles.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Free cell", image: "anySolitaireGames", difficulty: "", playerAmountLow: 1, playerAmountHigh: 1, materials: "\u{2022} At least 1 deck of cards", rules: "1. FreeCell is setup by creating eight columns of cards all face up. All 52 cards are used in the columns. The first four columns will have one more card than the other four columns.\n\n2. Move all the cards onto the foundation piles in number sequence. There are four foundation piles, one for each suit.\n\n3. Move cards around in three ways. One, by playing cards of a different color on top of a card that is one number higher. Two, by playing cards onto the foundation piles. Foundation piles are started with the ace in each suit, and can be played on in sequence up to the king in each suit. Three, move a card to one of the four free cells.\n\n4. Continue to move cards around in these three ways until all cards are moved to the foundation piles (win), or there are no more moves to be made (lose).\n\n5. When one of the eight columns is empty, any card can be moved into the open space.\n\n6. Only one card can be in each free cell at a time.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Pyramid", image: "anySolitaireGames", difficulty: "", playerAmountLow: 1, playerAmountHigh: 1, materials: "\u{2022} At least 1 deck of cards", rules: "1. The setup of the game is one of the key things that is different about this version from the original version. As usual, shuffle the deck. Deal cards to form a pyramid, starting with a row of 1 card, followed by a row of two cards, and so on, down to a row of 7 cards. Each row should overlap the previous one. The pyramid will include a total of 28 cards when complete. The remaining cards are set on the table face down to form the draw pile.\n\n2. Reveal cards from the draw pile, one at a time. If a card from the draw pile is not used, it should be covered up by the next card from the draw pile. It can be used later in the game, but only if it gets uncovered because any draw pile cards on top of it are able to be discarded.\n\n3. When two exposed cards total 13, they can be discarded. (This is why this version of the game is sometimes referred to as Solitaire 13.) Discarding is always optional, and there may be times when it is a better tactical choice not to discard.\n\n4. Cards in the pyramid are exposed if no cards are overlapping them. Only one card from the draw pile is exposed at any given time in the game (the most recent draw pile card to be turned up is the only card from the draw pile that's exposed).\n\n5. For example, if a 9 and a 4 are both exposed in the pyramid, they can be discarded.\n\n6. If a 5 is exposed in the pyramid and an 8 is exposed after being turned up from the draw pile, they can be discarded.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Tripeaks", image: "moreSolitairePhotos", difficulty: "", playerAmountLow: 1, playerAmountHigh: 1, materials: "\u{2022} At least 1 deck of cards", rules: "1. All building is carried out on the single waste pile. Any completely uncovered card in the tableau may be moved to the waste pile if it follows either an ascending or descending sequence regardless of suit. So in the above example, either the 6, the 6 or the 8 may be built on the 7.\n\n2. Sequences may turn the corner with Kings building on Aces and Aces building on Kings.\n\n3. When no more cards can be transferred from the tableau to the waste pile, a card from the stock is dealt to the waste pile and building resumes.\n\n4. When the stock is exhausted, and no more building can occur, then the game is over. You'll receive a bonus every time you completely demolish one of the three peaks and you'll also receive a bonus for each card that remains in the tableau when you win the game, along with another bonus depending on how fast you completed the game. Don't forget, you can double click or right click on a card to send it flying to the waste pile.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "active", title: "Blob tag", image: "active1", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022} People", rules: "1. Select 1 or 2 students to begin the blob.  The rest of the players will scatter about the playing area.  On the signal, the blob will attempt to tag the other players.  A player getting tagged, must join (literally, they must join a hand) the and continue developing the blob.  These 2 players must now stay joined and attempt to tag other players.  As more players get tagged, they must add onto the outside of the blob.  So, at any one time, the blob will only have two hands available for tagging (one on each end).  The more players that get tagged, the larger the blob grows.  The object of the game is to be the last player captured by the BLOB.  Following are some rules to follow:\n\n\t1.  Only the end players of the BLOB can tag others.\n\t2.  The BLOB must remain connected to tag others.\n\t3.  You may give a noodle to each free hand of the BLOB to aid in tagging.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "dice", title: "Bunco", image: "stuckInTheMudAndThreeOrMore", difficulty: "", playerAmountLow: 8, playerAmountHigh: 0, materials: "\u{2022} 2 Dice par table", rules: "1. Players divide into groups of four\n\n2. Each group of four should have a set of three dice.\n\n3. Each player should have a pencil and a scoresheet (free printable bunco score sheets)\n\n4. Each table of four players is numbered: Number One (head table), Two, Three, etc.\n\n5. In the first round, the Head Table begins to play, which signals other tables to begin as well.\n\n6. Each round has a target number. The target number of the first round is ones, so you try to roll ones with the dice.\n\n7. As your roll, record your target numbers as your roll them. For example, if you are playing ones, record each one that you roll.\n\n8. If you don't roll a one, it is the next players turn.\n\n9. Record your score, and combine it with the player across from you, who is considered your partner for that round.\n\n10. When one of the teams at the table reaches 21 points, play ends.\n\n11. Players then switch to another table. The winning team moves up a table, and the losing team stays where they are. The only exception is at the head table. The winners stay, and the losers move to the lowest table.\n\n11. The game can go on for as long as wanted.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "President", image: "forAnyCardGames", difficulty: "", playerAmountLow: 3, playerAmountHigh: 0, materials: "\u{2022}A deck of cards", rules: "1. Choose a dealer, they must deal one card at a time starting to the dealers left until all cards have been dealt.\n\n2. The player to the dealer's left starts by leading (face up) any single card or any set of cards of equal rank (for example three fives). Each player in turn must then either pass (i.e. not play any cards), or play face up a card or set of cards, which beats the previous play.\n\n3. Any higher single card beats a single card. A set of cards can only be beaten by a higher set containing the same number of cards. So for example if the previous player played two sixes you can beat this with two kings, or two sevens, but not with a single king, and not with three sevens (though you could play two of them and hang onto the third).\n\n4. It is not necessary to beat the previous play just because you can - passing is always allowed. Also passing does not prevent you from playing the next time your turn comes round.\n\n5. The play continues as many times around the table as necessary until someone makes a play which everyone else passes. All the cards played are then turned face down and put to one side, and the player who played last (and highest) to the previous trick starts again by leading any card or set of equal cards.\n\n6. The first player who is out of cards is awarded the highest social rank - this is President. The last player to be left with any cards is known as the Scum.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "strategy", title: "Mancala", image: "mancala", difficulty: "", playerAmountLow: 2, playerAmountHigh: 2, materials: "\u{2022}Mancala board, 48 colored plastic pieces (also called stones)", rules: "1. The game begins with one player picking up all of the pieces in any one of the pockets on their side.\n\n2. Moving counter-clockwise, the player deposits one of the stones in each pocket until the stones run out.\n\n3. If you run into your own Mancala (store), deposit one piece in it. If you run into your opponent's Mancala, skip it and continue moving to the next pocket.\n\n4. If the last piece you drop is in your own Mancala, you take another turn.\n\n5. If the last piece you drop is in an empty pocket on your side, you capture that piece and any pieces in the pocket directly opposite.\n\n6. Always place all captured pieces in your Mancala (store).\n\n7. The game ends when all six pockets on one side of the Mancala board are empty.\n\n8. The player who still has pieces on their side of the board when the game ends captures all of those pieces.\n\n9. Count all the pieces in each Mancala. The winner is the player with the most pieces.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Golf", image: "forAnyCardGames", difficulty: "", playerAmountLow: 2, playerAmountHigh: 4, materials: "\u{2022}One or two decks of cards", rules: "1. Two or three players use a standard 52- card deck. If played with four or more, a double-deck of 108 cards can be used.\n\n2. Each player is dealt six cards face down from the deck, the remainder is placed face down and the top card is turned up to start the discard pile beside it. Players arrange their cards in two rows of three in front of them, and turn any two of these cards face up. This arrangement is maintained throughout the game and players always have six cards in front of them.\n\n3. The object is for players to reduce the value of the cards in front of them by swapping them for lesser value cards and trying to get the lowest score. The highest score loses the game and the lowest score wins the game.\n\n4. Beginning at the dealer’s left, players take turns drawing single cards from either the stock or discard piles. The drawn card may either be swapped for one of that player’s six cards, or discarded. If the card is swapped for one of the face down cards, the card swapped in remains face up. If the card drawn is discarded, the player can then either flip a card or choose to make no move.\n\n5. The round ends when a player chooses to “knock” instead of taking their turn. Remaining players then have one turn to draw a card to improve their hands and then scores are totaled and recorded on a running score sheet. Each Jack or Queen scores 10 points, each King scores zero points, and each number card scores its face value.\n\n6. During play it is not legal for a player to pick up a card from the discard pile and return it to the discard pile without playing it, to allow another player to retrieve the card. A card picked up from the discard pile must be swapped with one of the current player’s cards.\n\n7. Game is nine or eighteen “holes” (deals), and the player with the lowest total score is designated winner.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Accordian", image: "anySolitaireGames", difficulty: "", playerAmountLow: 1, playerAmountHigh: 1, materials: "\u{2022}A deck of cards", rules: "1. All cards are dealt face up in a row, left to right, one card to a pile.\n\n2. Any pile can be moved onto the pile to its left, or the pile third to its left, provided the top cards of the piles match in either suit or rank.\n\n3. When you move a pile in the middle of the row, all the other piles are shifted to fill an empty space.\n\n4. You should select four cards of the same rank, clustered near each other and near the end of the layout. The strategy is to try to get all four selected cards to the end of the layout and never cover them with anything else until the very end of the game.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "King Albert", image: "anySolitaireGames", difficulty: "", playerAmountLow: 1, playerAmountHigh: 1, materials: "\u{2022}A deck of cards", rules: "1. Shuffle the deck and lay out nine tableau piles, fanned down. The first tableau has one card, the second two, the third three and so on, up to the ninth tableau which has nine cards.\n\n2. When this is done you will have seven cards left over; these form the reserve. All 52 cards should be placed face up. The four foundations start the game empty.\n\n3. Tableaus build down in alternate colors. Foundations build up in suit from the Ace. The seven cards in the reserve, and the top card of each tableau, are available for play on tableaus or foundations. Any available card can be placed in an empty tableau pile. Empty reserves cannot be filled, and must remain empty.\n\n4. The goal is to move all the cards to the foundations.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Gaps", image: "moreSolitairePhotos", difficulty: "", playerAmountLow: 1, playerAmountHigh: 1, materials: "\u{2022}A deck of cards", rules: "1. The cards are dealt into four rows of thirteen. The aces are removed and discarded from further play. The gaps that they leave behind are filled by cards that are the same suit and a rank higher than the card on the left of the gap. (For example, 4♣ can be placed beside 3♣.) However, any gap at the right of a King is considered dead and no card can fill it.\n\n2. Any gap on the left hand side of the row should be placed by a deuce and the row should be built up by suit beside the deuce (i. e. 2-3-4-5, etc.). It is the discretion of the player on which suit would occupy which row.\n\n3. When there are no more possible moves, the round is over. The cards that are not in order are gathered, making sure to leave any suit sequence (e.g., ♥2-3-4-5) behind. In Montana and Spaces, the cards are then shuffled; in Gaps, they are not. The cards are then redealt, making sure there is a gap in each row at the immediate right of each suit sequence or at the extreme left of the row if no suit sequence is formed in that row. There are only three rounds in the usual rules. But some variants allow four, and some have no limit.\n\n4. The game is won when all 48 cards are arranged in numerical order and in suits, with the gaps of each row beside the Kings at the extreme right hand of the row. The probability of winning depends on which rules are followed. In Spaces, where the cards are shuffled after each round and the rounds are limited to three, an experienced player will win perhaps one game in 20. In Gaps (cards are not shuffled, but the limit of three rounds remains), one win in seven games may be expected. If the number of rounds is not limited, winning is just a matter of time, whether the cards are shuffled or not.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Rummy", image: "forAnyCardGames", difficulty: "", playerAmountLow: 2, playerAmountHigh: 6, materials: "\u{2022}A deck of cards", rules: "1. K (high), Q, J, 10, 9, 8, 7, 6, 5, 4, 3, 2, A. (In many forms of Rummy, the ace may rank either high or low.)\n\n2. Dealer gives one card at a time face down, beginning with the player on the left. When two people play, each person gets 10 cards. When three or four people play, each receives seven cards; when five or six play, each receives six cards. The remaining cards are placed face down on the table, forming the stock.\n\n3. The top card of the stock is turned face up and becomes the upcard. It is placed next to the stock to start the discard pile.\n\n4. When two people play, the winner of each hand deals the next. When more than two play, the deal passes to the next player on the left.\n\n5. Each player tries to form matched sets consisting of groups of three or four of a kind, or sequences of three or more cards of the same suit.\n\n6. Beginning with the player to the left of the dealer, players either draw the top card of the stock or takes the top card of the discard pile and adds it to his hand. The player may also lay down on the table, face up, any meld (matched set). If the player does not wish to lay down a meld, he discards one card face up, onto the discard pile. If the player has drawn from the discard pile, he may not discard the same card on that turn.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Slapjack", image: "forAnyCardGames", difficulty: "", playerAmountLow: 2, playerAmountHigh: 0, materials: "\u{2022}A deck of cards", rules: "1. The goal is to win all the cards, by being first to slap each jack as it is played to the center.\n\n2. Deal cards one at a time face down to each player until all the cards have been dealt. The hands do not have to come out even. Without looking at any of the cards, each player squares up their hand into a neat pile in front of them.\n\n3. Beginning on the dealer’s left, each player lifts one card at a time from their pile and places it face up in the center of the table.\n\n4. When the card played to the center is a jack, the fun begins! The first player to slap their hand down on the jack takes it, as well as all the cards beneath it. The player winning these cards turns them face down, places them under their pile of cards, and shuffles them to form a new, larger pile.\n\n5. When more than one player slaps at a jack, the one whose hand is directly on top of the jack wins the pile. If a player slaps at any card in the center that is not a jack, they must give one card, face down, to the player of that card. When a player has no more cards left, they remain in the game until the next jack is turned. The player may slap at the jack in an effort to get a new pile. If the player fails to win that next pile, they are out of the game.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Bingo", image: "forAnyCardGames", difficulty: "", playerAmountLow: 3, playerAmountHigh: 0, materials: "\u{2022}2 decks of cards", rules: "1. From the first deck of cards, five cards are dealt to each player face up. There will be players and one Caller who will call out the card values that players must match in order to complete their Bingo hand.\n\n2. From the second deck of cards, the Caller will select a card, one at a time, and call out the rank and suit of the card - for example queen of hearts. The player with the called card turns it face down. The first player to turn all their cards face down wins.", favorite: false, gameIndex: index))
    index += 1
    
    tempGames.append(Game(catagory: "card", title: "Emperor", image: "moreSolitairePhotos", difficulty: "", playerAmountLow: 1, playerAmountHigh: 1, materials: "\u{2022}A deck of cards", rules: "1. The goal is to get all eight foundations built up from ace through king.\n\n2. Deal Ten piles of four cards each, dealt by rows, the first three rows face down, and the last row face up. Remaining cards are placed in a pile to form the Stock.\n\n3. Cards are turned up one at a time from the top of the stock and may be placed on the piles or foundations. Cards from the stock that cannot be used are placed face up in a pile below the rows to form the waste pile. The top card of the waste pile is always available for building onto the piles or foundations. The player may overlap the waste pile cards so that all of them can be seen.\n\n4. All aces are placed in a Foundation row above the Ten dealt piles as soon as the player can release them from the piles.\n\n5. Only the top card of a pile may be moved. The removal of a card releases the one below it. A card may be placed only on a card of the opposite color and next-lower in rank (A 7 of Clubs may be placed only on 6 of Hearts).\n\n6. A king may not be built on an ace, and aces must be placed as foundations as soon as possible. Foundations are built up in suit and sequence from ace through king. When any of the ten piles is entirely cleared away, any movable card may be placed in the space.", favorite: false, gameIndex: index))
    index += 1

    
    
    return tempGames
}
